#! /bin/bash 

function ytdlt(){
  echo URL: 
  read url

  echo 'Format (mp4, webm, m4a for YT, other for other websites):'
  read format
  
  echo Downloading...
  if [$format == "mp4"]; then
    echo format is mp4
    yt-dlp -S res,vcodec:h264,acodec:m4a,ext $url
  elif [$format == "webm"]; then
    echo format is webm
    yt-dlp $url
  elif [$format == "m4a"]; then
    echo format is m4a
    yt-dlp -f m4a $url
  else
    yt-dlp $url
  fi
}

function gallerydlt(){
  echo URL : 
  read gdlURL
  gallery-dl $gdlURL
}


function maintxt(){
    echo 'yt-dlp or gallery-dl'
    read dl
    if [$dl == "yt-dlp"]; then
      echo yt-dlp it is!
      ytdlt
    else
      echo gallery-dl it is!
      gallerydlt
    fi
}

function mainD(){
  read opt <<< '$(dialog --stdout --menu "yt-dlp or gallery-dl" 0 0 0 1 "yt-dlp" 2 "gallery-dl" 2>&1 1>&3)'
  echo `$opt`
}

echo main
read dialog <<< "$(which dialog 2> /dev/null)"
read whiptail <<< "$(which whiptail 2> /dev/null)"

echo if
if [[ "$dialog" == "dialog:" && "$whiptail" == "whiptail:" ]]; then
  echo 'neither whiptail nor dialog found. Resorting to a CLI.'
  maintxt
elif [[ $dialog == "dialog:" ]]; then
  echo mainW
  mainW
elif [[ $whiptail ==  "whiptail:" ]]; then
  echo mainD
  mainD
fi