#! /bin/bash 
: '
This file is part of Da Cool Media Downloader.

Da Cool Media Downloader is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

Da Cool Media Downloader is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with Da Cool Media Downloader. If not, see <https://www.gnu.org/licenses/>.
'


# text cli
function ytdlt(){
  echo URL: 
  read url

  echo 'Format (mp4, webm, m4a for YT, default for other websites):'
  read format
  
  echo Downloading...
  if [$format == "mp4"]; then
    echo format is mp4
    yt-dlp -S res,vcodec:h264,acodec:m4a,ext $url
  elif [$format == "webm"]; then
    echo format is webm
    yt-dlp $url
  elif [$format == "m4a"]; then
    echo format is m4a
    yt-dlp -f m4a $url
  else
    yt-dlp $url
  fi
}

function gallerydlt(){
  echo URL : 
  read gdlURL
  gallery-dl $gdlURL
}


function maintxt(){
echo 'yt-dlp or gallery-dl (or exit)'
read dl
if [$dl == "yt-dlp"]; then
  echo yt-dlp it is!
  ytdlt
elif [[$dl == "gallery-dl"]];then
  echo gallery-dl it is!
  gallerydlt
else
  exit 1
fi
}

# Dialog use

function gallerydld() {
  read gdURL <<< $(dialog --stdout --inputbox "URL" 0 0 "URL" 2>&1 1>&3)
  gallery-dl $gdURL
}

function ytdld(){
  read uRl <<< $(dialog --stdout --inputbox "URL" 0 0 "url" 2>&1 1>&3)
  read format <<< $(dialog --stdout --menu "Format (mp4/webm/m4a/default)" 0 0 0 1 "mp4" 2 "webm" 3 "m4a" 4 "default" 2>&1 1>&3)
  if [[ $format == "1" ]];then
    yt-dlp -S res,vcodec:h264,acodec:m4a,ext $uRl
  elif [[ $format == "2" ]]; then
    yt-dlp $uRl
  elif [[ $format == "3" ]]; then
    yt-dlp -f m4a $uRl
  else
    yt-dlp $uRl
  fi
}

function mainD(){
  read opt <<< $(dialog --stdout --menu "yt-dlp or gallery-dl" 0 0 0 1 "yt-dlp" 2 "gallery-dl" 2>&1 1>&3)
  if [[ $opt == "1" ]];then
    dialog --msgbox "yt-dlp it is!" 0 0
    ytdld
  elif [[ $opt == "2" ]];then
    dialog --msgbox "gallery-dl it is!" 0 0
    gallerydld
  else
  exit 1
  fi
}

# Whiptail use

function ytdlw() {
  read UrL <<< $(whiptail --inputbox "URL" $(stty -a | tr \; \\012 |egrep 'rows|columns' | cut '-d ' -f3) "url" 3>&1 1>&2 2>&3)
  read fmt <<< $(whiptai; --menu "Format (mp4/webm/m4a/default)" $(stty -a | tr \; \\012 |egrep 'rows|columns' | cut '-d ' -f3) 0 1 "mp4" 2 "webm" 3 "m4a" 4 "default" 3>&1 1>&2 2>&3)
  if [[ $fmt == "1" ]];then
    yt-dlp -S res,vcodec:h264,acodec:m4a,ext $UrL
  elif [[ $fmt == "2" ]];then
    yt-dlp $UrL
  elif [[ $fmt == "3" ]];then
    yt-dlp -f m4a $UrL
  else
    yt-dlp $UrL
  fi
}

function gallerydlw() {
  read gdURL <<< $(whiptail --inputbox "URL" $(stty -a | tr \; \\012 |egrep 'rows|columns' | cut '-d ' -f3) "URL" 3>&1 1>&2 2>&3)
  gallery-dl $gdURL
}

function mainW(){
  read to <<< $(whiptail --menu "yt-dlp or gallery-dl" $(stty -a | tr \; \\012 |egrep 'rows|columns' | cut '-d ' -f3) 0 1 "yt-dlp" 2 "gallery-dl" 3>&1 1>&2 2>&3)
  if [[ $to == "1" ]];then
    whiptail --msgbox "yt-dlp it is!" $(stty -a | tr \; \\012 |egrep 'rows|columns' | cut '-d ' -f3)
    ytdlw
  elif [[ $to == "2" ]];then
    whiptail --msgbox "gallery-dl it is!" $(stty -a | tr \; \\012 |egrep 'rows|columns' | cut '-d ' -f3)
    gallerydlw
  else
  exit 1
  fi
}

function helptxt(){
  echo "dcmd (c) 2024 oofybruh9. Licensed under GPLv3"
  echo 
  echo "Usage dcmd [-h][--help][-y][-g][-ee][-u][-f] (parameters are optional):"
  echo "  -h --help     Print help and exit"
  echo "  -y            Use yt-dlp and only prompt other stuff"
  echo "  -g            Use gallery-dl and only prompt URL"
  echo "  -u -URL       Use URL prompted (requires -y or -g flag)"
  echo "  -f            Add flags to the downloader (requires -y or -g flag)"
  echo "  -ee           ë̴̠̫́̓͠x̵̠̞̓͊͜͝e̸̻̺͕͋͐͠c̴͔͉͍̒͆̚u̵̼͖̪͆͐̿t̵̞͚̟̔͒͠e̸̡͙̘̾͝͝ i̴͓͚͑̈́͝t̵͖̝͙̔͑͝ t̸̡͓̝̾͛͋o̴̪͓̠͌̕ f̸͉̞̟͆̚͝ḯ̸̙̘̾͊n̴̢̠͖̐̈́͋d̵͓͉̀̾̈́ o̵̘͎̔͜͝͠u̸͚͉͖̓͛̔t̴̡͖͇͋́͝…̸̡̘̦̈́͊"
}

if [[$1 == "-h" || "--help"]];then
  helptxt
  sleep 1
  exit 1
  break
else
echo main
read dialog <<< "$(which dialog 2> /dev/null)"
read whiptail <<< "$(which whiptail 2> /dev/null)"

echo if
if [[ "$dialog" != "/usr/bin/dialog" && "$whiptail" != "/usr/bin/whiptail" ]]; then
  echo 'neither whiptail nor dialog found. Resorting to a CLI.'
  maintxt
elif [[ $dialog != "/usr/bin/dialog" ]]; then
  echo mainW
  mainW
else
  echo mainD
  mainD
fi
fi