#! /bin/bash

:'
This file is part of Da Cool Media Downloader.

Da Cool Media Downloader is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

Da Cool Media Downloader is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with Da Cool Media Downloader. If not, see <https://www.gnu.org/licenses/>.
'

# python upgrade
echo Verifying Python is a thing...

python3 --version

echo Upgrading pip

python3 -m pip install --upgrade pip

# installing the services
echo installing yt-dlp

pip install yt-dlp

echo installing gallery-dl

pip install gallery-dl

echo setting up configs

touch ~/gallery-dl.conf
touch ~/yt-dlp.conf

ln -s ~/yt-dlp.conf /workspaces/da-Cool-Media-DL/yt-dlp.conf
ln -s ~/gallery-dl.conf /workspaces/da-Cool-Media-Dl/gallery-dl.conf

# ffmpeg for 1080p or higher

sudo apt install ffmpeg

# yay it finished!
echo Finished! for now...
