#! /bin/bash

: '
This file is part of Da Cool Media Downloader.

Da Cool Media Downloader is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

Da Cool Media Downloader is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with Da Cool Media Downloader. If not, see <https://www.gnu.org/licenses/>.
'

function yesno() {
  answer=$(whiptail --yesno "$1" 0 0 3>&1 1>&2 2>&3; echo $?)
  echo "Answer is $answer"
}

function yt-dlpSYS() {
    arch=`uname -i`
    if [$arch == "x86_64"]; then
        echo '64 bit'
    fi
}

echo ➜
yesno "➜ Install system-wide?"


if [$answer = 0]; then
    echo yes
    yt-dlpSYS
else
    echo no
fi
